const passengerInput = document.getElementById('passenger');
passengerInput.addEventListener('click', () => {
  alert('اینجا بعداً منوی انتخاب تعداد مسافر باز می‌شود!');
});
const bor0 = document.querySelector(".bor0")
const bor1 = document.querySelector(".bor1")
const bor2 = document.querySelector(".bor2")
const bor3 = document.querySelector(".bor3")
const bor4 = document.querySelector(".bor4")
const bor5 = document.querySelector(".bor5")
const bor6 = document.querySelector(".bor6")
const a0 = document.querySelector(".a0")
const a1 = document.querySelector(".a1")
const a2 = document.querySelector(".a2")
const a3 = document.querySelector(".a3")
const a4 = document.querySelector(".a4")
const box0 = document.querySelector(".box0")
const box11 = document.querySelector(".box11")
bor0.addEventListener("click",() => {
    a0.classList.remove('hidden')
    a1.classList.add('hidden')
    a2.classList.add('hidden')
    a3.classList.add('hidden')
    a4.classList.add('hidden')
    box0.classList.add('hidden')
    box11.classList.add('hidden')
    bor1.classList.remove('bor')
    bor1.classList.add('bor0')
    bor2.classList.remove('bor')
    bor2.classList.add('bor0')
    bor3.classList.remove('bor')
    bor3.classList.add('bor0')
    bor4.classList.remove('bor')
    bor4.classList.add('bor0')
    bor5.classList.remove('bor')
    bor5.classList.add('bor0')
    bor6.classList.remove('bor')
    bor6.classList.add('bor0')
    bor0.classList.toggle('bor')
})
bor1.addEventListener("click",() => {
    a1.classList.remove('hidden')
    a2.classList.add('hidden')
    a3.classList.add('hidden')
    a4.classList.add('hidden')
    box0.classList.add('hidden')
    box11.classList.add('hidden')
    bor0.classList.remove('bor')
    bor0.classList.add('bor0')
    bor2.classList.remove('bor')
    bor2.classList.add('bor0')
    bor3.classList.remove('bor')
    bor3.classList.add('bor0')
    bor4.classList.remove('bor')
    bor4.classList.add('bor0')
    bor5.classList.remove('bor')
    bor5.classList.add('bor0')
    bor6.classList.remove('bor')
    bor6.classList.add('bor0')
    bor1.classList.toggle('bo1')
    bor1.classList.toggle('bor')
})
bor2.addEventListener("click",() => {
    a1.classList.add('hidden')
    a2.classList.remove('hidden')
    a3.classList.remove('hidden')
    a4.classList.remove('hidden')
    box0.classList.add('hidden')
    box11.classList.add('hidden')
    bor1.classList.remove('bor')
    bor1.classList.add('bor1')
    bor0.classList.remove('bor')
    bor0.classList.add('bor0')
    bor3.classList.remove('bor')
    bor3.classList.add('bor0')
    bor4.classList.remove('bor')
    bor4.classList.add('bor0')
    bor5.classList.remove('bor')
    bor5.classList.add('bor0')
    bor6.classList.remove('bor')
    bor6.classList.add('bor0')
    bor2.classList.toggle('bo2')
    bor2.classList.toggle('bor')
})
bor3.addEventListener("click",() => {
    a0.classList.add('hidden')
    a1.classList.add('hidden')
    a2.classList.add('hidden')
    a3.classList.add('hidden')
    a4.classList.add('hidden')
    box0.classList.add('hidden')
    box11.classList.add('hidden')
    bor2.classList.remove('bor')
    bor2.classList.add('bor2')
    bor0.classList.remove('bor')
    bor0.classList.add('bor0')
    bor4.classList.remove('bor')
    bor4.classList.add('bor0')
    bor5.classList.remove('bor')
    bor5.classList.add('bor0')
    bor6.classList.remove('bor')
    bor6.classList.add('bor0')
    bor3.classList.toggle('bo3')
    bor3.classList.toggle('bor')
})
bor4.addEventListener("click",() => {
    a0.classList.add('hidden')
    a1.classList.add('hidden')
    a2.classList.add('hidden')
    a3.classList.add('hidden')
    a4.classList.add('hidden')
    box0.classList.remove('hidden')
    box11.classList.remove('hidden')
    bor3.classList.remove('bor')
    bor3.classList.add('bor3')
    bor0.classList.remove('bor')
    bor0.classList.add('bor0')
    bor2.classList.remove('bor')
    bor2.classList.add('bor0')
    bor5.classList.remove('bor')
    bor5.classList.add('bor0')
    bor6.classList.remove('bor')
    bor6.classList.add('bor0')
    bor4.classList.toggle('bo4')
    bor4.classList.toggle('bor')
})
bor5.addEventListener("click",() => {
    a0.classList.add('hidden')
    a1.classList.add('hidden')
    a2.classList.add('hidden')
    a3.classList.add('hidden')
    a4.classList.add('hidden')
    box0.classList.add('hidden')
    box11.classList.add('hidden')
    bor4.classList.remove('bor')
    bor4.classList.add('bor4')
    bor0.classList.remove('bor')
    bor0.classList.add('bor0')
    bor2.classList.remove('bor')
    bor2.classList.add('bor0')
    bor3.classList.remove('bor')
    bor3.classList.add('bor0')
    bor6.classList.remove('bor')
    bor6.classList.add('bor0')
    bor5.classList.toggle('bo5')
    bor5.classList.toggle('bor')
})
bor6.addEventListener("click",() => {
    a0.classList.add('hidden')
    a1.classList.add('hidden')
    a2.classList.add('hidden')
    a3.classList.add('hidden')
    a4.classList.add('hidden')
    box0.classList.add('hidden')
    box11.classList.add('hidden')
    bor5.classList.remove('bor')
    bor5.classList.add('bor5')
    bor0.classList.remove('bor')
    bor0.classList.add('bor0')
    bor2.classList.remove('bor')
    bor2.classList.add('bor0')
    bor3.classList.remove('bor')
    bor3.classList.add('bor0')
    bor4.classList.remove('bor')
    bor4.classList.add('bor0')
    bor6.classList.toggle('bo6')
    bor6.classList.toggle('bor')
})